version: '3.8'
services:

  #PHP Service
  api:
    build: .
    restart: unless-stopped
    volumes:
        - .:/var/www/imusic_api
        
  #Nginx Service
  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/imusic_api
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #DB
  db:
    image: mariadb:10.5.8
    environment: 
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "imusic"
    ports:
     - "2105:3306"